#!/bin/bash

set -e
export CC=gcc

echo "==> Initing Git submodules"

git submodule update --init --recursive

echo "==> Installing required libraries…"

if [ "$(uname)" == "Darwin" ]; then
  brew install glib gdk-pixbuf cairo pango libffi
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  sudo apt-get -qq -y install libxml2-dev libcairo2-dev libpango1.0-dev libffi-dev ttf-lyx
fi

if [ "$1" != "--production" ]; then
  BRANCH="master"
  echo "==> Installing dependencies…"

  npm install --ignore-scripts
fi
