#!/bin/bash

set -e

if [ -z "$1" ]; then
  BRANCH="master"
else
  BRANCH=$1
fi

cd deps/mtex2MML
git fetch origin
git checkout $BRANCH && git pull
sha=`git rev-parse HEAD`
cd ../..
git add deps/mtex2MML
git commit -m "Update mtex2MML to ${sha}"

cd deps/lasem
git fetch origin
git checkout master && git reset --hard origin/master
sha=`git rev-parse HEAD`
cd ../..
git add deps/lasem
git commit -m "Update Lasem to ${sha}"
